name: plist_generator
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4

  propertylistserialization: ^1.4.1

dev_dependencies:
  fl_common_lint: ^1.8.0

  http: ^1.5.0
